
DATASET ACTIVATE DataSet0.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE ZPP
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN 
  /DEPENDENT weightgain
  /METHOD=ENTER Initialweight initialage
  /RESIDUALS NORMPROB(ZRESID)
  /SAVE PRED.
